#! /usr/bin/env python

import os
import json

# Parse a config file
def parse_config(config_json_file):
    """
    Take a json file, read and return the contents
    """

    if not os.path.isfile(config_json_file):
        raise ValueError('No config file could be found!')

    # Read the config json file
    with open(config_json_file, 'r') as jsonfile:
        config = json.load(jsonfile)

    return config

if __name__ == '__main__':

    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('--config_file', type=str, dest="config_file", default='/flywheel/v0/config.json', help='Full path to the input json config file.')
    ap.add_argument('--debug', '-d', type=bool, dest="debug", default=False, help='show debug print statements')
    args = ap.parse_args()

    config = parse_config(args.config_file)

    flywheel_input = '/flywheel/v0/input/'

    # Establish time base for the PPG data
    niftiinfo = config['inputs']['nifti']['object']['info']
    TR = niftiinfo['RepititionTime']
    nvols = niftiinfo['NumberOfTemporalPositions']

    # Unzip physio data 
    physiofile = config['inputs']['gephysio']['location']['path']
    os.system(("gunzip %s -C %s", % (flywheel_input, physiofile)))
    physio_dir = flywheel_input+os.path.basename(physiofile)
    
    cmd = ("run_gephysio.sh /opt/mcr/v95 %s %d %d" %( physio_dir, TR, nvols))
    os.system(cmd)


